name: Test Runner
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch: {}

jobs:
  test:
    name: Run EditMode Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out my unity project.
        uses: actions/checkout@v4

      - name: Run EditMode Test
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: 2022.3.10f1
          testMode: EditMode

      # テストの実行結果をアーティファクトにアップロードしてダウンロードして参照できるようにする
      # - uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: Test results
      #     path: artifacts